---
version: '2'

services:

  django:
    ports:
      - "8080"
    volumes:
      - ../application:/opt/django_development:rw
    working_dir: /opt/django_development
    command: bash -c "until python manage.py inspectdb; do sleep 1; done &&
     python manage.py runserver 0.0.0.0:8080;"

  postgres:
    ports:
      - "{{ cookiecutter.db_port }}"